//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.14
//

import UIKit
import AWSMobileHubHelper
import AWSIoT

class MainViewController: UITableViewController {
    
    var demoFeatures: [DemoFeature] = []
    

    
    // MARK: - View lifecycle
    //Mainのviewを作成している部分
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
        
        // Default theme settings.
        navigationController!.navigationBar.backgroundColor = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
        //navigationController!.navigationBar.barTintColor = UIColor(red: 0xF5/255.0, green: 0x20/255.0, blue: 0x70/255.0, alpha: 1.0)
        navigationController!.navigationBar.barTintColor = #colorLiteral(red: 0, green: 0.4549019608, blue: 0.4117647059, alpha: 1)//UIColor(red:17/255.0, green:128/255.0, blue:255/255.0, alpha:1.0)
        navigationController!.navigationBar.tintColor = UIColor.white


        var demoFeature = DemoFeature.init(
            name: NSLocalizedString("User Sign-in",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Enable user login with popular 3rd party providers.",
                comment: "Description for demo menu option."),
            icon: "", storyboard: "UserIdentity")
        
        //demoFeatures.append(demoFeature)
        

        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Air Conditionar",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString(//"Run business logic in the cloud without managing servers. Integrate functionality with your app using APIs."
                "Controlling air conditionar: turn on/off, logging temperature history.",
                comment: "Description for demo menu option."),
            icon: "autoioIcon", storyboard: "Autoio")
        
        demoFeatures.append(demoFeature)
        
        
    }

    

    
    // MARK: - UITableViewController delegates
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MainViewCell")!
        let demoFeature = demoFeatures[indexPath.row]
        cell.imageView!.image = UIImage(named: demoFeature.icon)
        cell.textLabel!.text = demoFeature.displayName
        cell.detailTextLabel!.text = demoFeature.detailText
        return cell
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return demoFeatures.count
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let demoFeature = demoFeatures[indexPath.row]
        let storyboard = UIStoryboard(name: demoFeature.storyboard, bundle: nil)
        let viewController = storyboard.instantiateViewController(withIdentifier: demoFeature.storyboard)
        self.navigationController!.pushViewController(viewController, animated: true)
    }
    
   
    

    
    
}
//以下はただの< Back buttonのみの実装
/**
class FeatureDescriptionViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem.init(title: "Back", style: .plain, target: nil, action: nil)
    }
}
**/
